Documentation:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Metrics/BlockLength:
    Enabled: false

Metrics/LineLength:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Style/IndentationWidth:
    Width: 1

Style/NumericLiterals:
    Enabled: false

Style/Tab:
    Enabled: false
